### ISSUE TITLE
Feature Request: Calendar

### ISSUE THREAD

**Issue by sauricat** [one-among-us/about-site#13]
这个卡片。Calendar 里面可以显示将来的所有活动吗？喵~
![image](https://github.com/user-attachments/assets/ba0d82e9-1cc4-4b4a-a618-ee6d194819a2)

**Comment by BeiyanYunyi** [comment]
🤔

**Comment by Linzh7** [comment]
个人的记忆中，之前提供了一个 似乎是 google/ms 自带的组件来完成所有信息的更新。或许（不确定）是考虑到页面内容较多、设计风格不搭配等被移除了……

不过，从我的观点，我可能喜欢时间降序排列，因为我看到第一个 15 后以为没有在这周末前的东西了（然后打开订阅的 calendar 发现有一个我很想参加的活动在后面耶qwq\\\

**Comment by sauricat** [comment]
现在的不知道是不是按照 ical 文件的顺序（也就是 google calendar 的编辑顺序）显示的，感觉需要加一个排序后输出？

**Comment by LS-KR** [comment]
> 个人的记忆中，之前提供了一个 似乎是 google/ms 自带的组件来完成所有信息的更新。或许（不确定）是考虑到页面内容较多、设计风格不搭配等被移除了……
> 
> 不过，从我的观点，我可能喜欢时间降序排列，因为我看到第一个 15 后以为没有在这周末前的东西了（然后打开订阅的 calendar 发现有一个我很想参加的活动在后面耶qwq\\

把 https://github.com/one-among-us/about-site/blob/main/content/Calendar.vue#L56 改成这个就好了?

``` ts
    evs.value = events
      .sort((a, b) => {
        if (a.start && b.start) return a.start.getTime() - b.start.getTime();
        return 0;
      })
      .reverse();
```
