### ISSUE TITLE
[Feature Request] Recursively add articles in `content/posts`

### ISSUE THREAD

**Issue by sauricat** [one-among-us/about-site#17]
I am thinking of the possibility of dividing articles into `content/posts` into smaller separate directories, such as notifications & announcements, docs for one-among.us, docs for local community, etc. 

The official implement of this requires manually adding items in `content/.vitepress/config.ts`, while thanks to 云依 we have a `content/.vitepress/theme/utils/getPostList.ts`. 

https://github.com/one-among-us/about-site/blob/9a42e47e19ea99a3e45c0c95920a68ca8ab82ac5/content/.vitepress/theme/utils/getPostList.ts#L3-L31 

What do you think about rewriting this? Also, there must be something to update accordingly in `content/posts/index.vue`.

https://github.com/one-among-us/about-site/blob/9a42e47e19ea99a3e45c0c95920a68ca8ab82ac5/content/posts/index.vue#L21

**Comment by sauricat** [comment]
Also, `content/${locale}/posts`.

**Comment by BeiyanYunyi** [comment]
pending.

**Comment by BeiyanYunyi** [comment]
`content/.vitepress/theme/utils/getPostList.ts` have been not used since `getPostList.data.ts` was introduced. Deleting it is safe.

**Comment by BeiyanYunyi** [comment]
What're you requesting for? A auto-generated sidebar, or make post list (such as `content/zh-Hans/posts/index.vue`) available in recurred folders?

The former has been implemented in #18.
