### ISSUE TITLE
Add multilanguage support for oneamongus.ca

### ISSUE THREAD

**Issue by sauricat** [one-among-us/about-site#3]
这个站做成多语言有没有困难？目测可以加中文和日文之类的。尤其是 Links（就是很多组织都有的 link tree，我们 host 在自己网站上就可以了）。

@BeiyanYunyi 由于这个站是你之前搭建的，麻烦说一下想法。如果不是很空闲的话，具体实现可以让我们其他朋友来操作。

cc 技术支援组 @artefaritaKuniklo

**Comment by BeiyanYunyi** [comment]
没有困难。

https://vitepress.dev/guide/i18n

今天或者明天我抽空做一下。

**Comment by BeiyanYunyi** [comment]
https://github.com/one-among-us/about-site/tree/i18n ，目前的做法是：英语放在根目录，其他语言放在其对应目录。例：`/zh-cn/posts`。需要注意的地方有如下几处：

- `/content/.vitepress/config.ts` 的 `rewrite` 配置。
- 同上，`locales` 配置。
- 各文档内部的链接，需要修改为链接至自己语言页的页面，如 `/posts` 修改为 `/zh-cn/posts`

路径名具体应当采用哪种方案，如使用 zh-cn 还是 zh-Hans（我的建议是后者），有待进一步讨论。

**Comment by artefaritaKuniklo** [comment]
> https://github.com/one-among-us/about-site/tree/i18n ，目前的做法是：英语放在根目录，其他语言放在其对应目录。例：`/zh-cn/posts`。需要注意的地方有如下几处：
> 
> * `/content/.vitepress/config.ts` 的 `rewrite` 配置。
> * 同上，`locales` 配置。
> * 各文档内部的链接，需要修改为链接至自己语言页的页面，如 `/posts` 修改为 `/zh-cn/posts`
> 
> 路径名具体应当采用哪种方案，如使用 zh-cn 还是 zh-Hans（我的建议是后者），有待进一步讨论。

和.us站统一起来的话用的是zh-Hans

**Comment by sauricat** [comment]
Temporarily solved. We can add more languages in the future. I suggest not closing the issue for now.
